# +- - - - - - - - - - - - - - - - - -+
# | HiddenArmor - Configuration File  |
# +- - - - - - - - - - - - - - - - - -+

# Invisibility potion effect related section
invisibility-potion:
  # 隐身时是否隐藏装备.
  always-hide-gear: false

# Equipments to be ignored and not hidden section
ignore:
  # If leather armor should not be hidden and be shown even if the player is hiding his armor.
  # It is recommended to set this to true due to powder snow issues caused when the leather armor is hidden.
  leather-armor: true

  # 是否隐藏海龟壳.
  turtle-helmet: false

  # Set this to true if you want elytras to never be hidden.
  # If this is set to false, the elytra will only be hidden to other players due to minecraft limitations.
  elytra: false


# Set to true if you want the command to be allowed to all players by default or to false if you want
# the command to be allowed only to OPs and players with its permission.
default-permissions:
  # Command: /togglearmor
  # Description: Toggle the player's own armor visibility
  # Permission: hiddenarmor.toggle
  #玩家是否可以用/togglearmor 来切换装备可见度
  toggle: true

  # Command: /togglearmor <player>
  # Description: Toggle other player's armor visibility
  # Permission: hiddenarmor.toggle.other
  #玩家是否可以用/togglearmor <player> 来切换其他玩家的可见度
  toggle-other: false

# Used to inform when a new config update is available, don't change this
config-version: 1
